[workspace]
members = [
    "crates/fastest-core",
    "crates/fastest-python",
    "crates/fastest-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Deren S <derens99@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
pyo3 = "0.25"
anyhow = "1.0"
thiserror = "1.0"
walkdir = "2.5"
num_cpus = "1.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
indicatif = "0.17"

