[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-rust>=1.5.2"]
build-backend = "setuptools.build_meta"

[project]
name = "fastest-runner"
version = "0.1.0"
description = "A blazing fast Python test runner built with Rust"
readme = "README.md"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Unit",
]
requires-python = ">=3.8"
keywords = ["testing", "test-runner", "pytest", "performance", "rust"]

[project.urls]
Homepage = "https://github.com/yourusername/fastest"
Documentation = "https://github.com/yourusername/fastest/tree/main/docs"
Repository = "https://github.com/yourusername/fastest"
Issues = "https://github.com/yourusername/fastest/issues"
Changelog = "https://github.com/yourusername/fastest/blob/main/CHANGELOG.md"

[project.scripts]
fastest = "fastest_runner:main"

[tool.cibuildwheel]
# Build for common platforms
build = ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
skip = ["*-musllinux_*", "*-win32", "pp*"]

# Use rustup to install Rust
before-all = "curl https://sh.rustup.rs -sSf | sh -s -- -y"
environment = { PATH = "$HOME/.cargo/bin:$PATH" }

[tool.cibuildwheel.linux]
before-all = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y",
    "yum install -y openssl-devel || apt-get update && apt-get install -y libssl-dev"
]

[tool.cibuildwheel.macos]
before-all = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y",
    "rustup target add aarch64-apple-darwin"
]

[tool.cibuildwheel.windows]
before-all = [
    "rustup-init.exe -y",
    "rustup target add i686-pc-windows-msvc"
] 