[package]
name = "fastest-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
walkdir.workspace = true
num_cpus.workspace = true
serde.workspace = true
serde_json.workspace = true
colored.workspace = true
indicatif.workspace = true
dirs = "5.0"
rayon = "1.8"
dashmap = "5.5"
tree-sitter = "0.22"
tree-sitter-python = "0.21"
once_cell = "1.19"
toml = "0.8"
parking_lot = "0.12"
notify = "6.1"
similar = "2.4" 