[package]
name = "fastest-core"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
walkdir.workspace = true
num_cpus.workspace = true
serde.workspace = true
serde_json.workspace = true
colored.workspace = true
indicatif.workspace = true
clap.workspace = true

# Non-workspace dependencies
chrono = "0.4"
crossbeam = "0.8"
dashmap = "6.1"
dirs = "5.0"
futures = "0.3"
glob = "0.3"
ignore = "0.4"
itertools = "0.10"
notify = "6.0"
once_cell = "1.17"
parking_lot = "0.12"
quick_cache = "0.6"
rand = "0.8"
rayon = "1.10"
regex = "1.11"
tempfile = "3.2"
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
which = "7.0"
rustpython-parser = "0.3"
tree-sitter = "0.22"
tree-sitter-python = "0.21"
similar = "2.4"
sha2 = "0.10"
toml = "0.8"

# Plugin system dependencies
inventory = "0.3"         # Plugin discovery and registration
linkme = "0.3"           # Static plugin linking
libloading = "0.8"       # Dynamic plugin loading
async-trait = "0.1"      # Async trait support
sysinfo = "0.30"         # System information
uuid = { version = "1.0", features = ["v4"] }  # UUID generation
pyo3 = { version = "0.19", features = ["auto-initialize"] }  # Python integration

# Phase 3: Advanced Features dependencies
git2 = "0.18"                     # Git integration for incremental testing
petgraph = "0.6"                  # Dependency graph management
priority-queue = "2.0"            # Test prioritization
blake3 = "1.5"                    # Fast hashing for change detection
memmap2 = "0.9"                   # Memory-mapped file access
flate2 = "1.0"                    # Compression for caches
lru = "0.12"                      # LRU cache for test results
rmp-serde = "1.3"                # MessagePack serialization
semver = "1.0"                   # Version comparison
tar = "0.4"                      # Tar extraction
ureq = { version = "2.9", features = ["json"] }  # HTTP requests
zip = "0.6"                      # Zip extraction

# Phase 4: Developer Experience dependencies
serde_repr = "0.1"               # Enum serialization for LSP
# tower = "0.4"                    # Service abstractions for LSP
# tower-lsp = "0.20"               # Language Server Protocol implementation
# tokio-util = "0.7"               # Tokio utilities for LSP
# ropey = "1.6"                    # Rope data structure for text editing

[dev-dependencies]
tempfile = "3.8" 