[package]
name = "fastest-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
walkdir.workspace = true
num_cpus.workspace = true
serde.workspace = true
serde_json.workspace = true
colored.workspace = true
indicatif.workspace = true
clap.workspace = true

# Non-workspace dependencies
chrono = "0.4"
crossbeam = "0.8"
dashmap = "6.1"
dirs = "5.0"
futures = "0.3"
glob = "0.3"
ignore = "0.4"
itertools = "0.10"
notify = "6.0"
once_cell = "1.17"
parking_lot = "0.12"
quick_cache = "0.6"
rand = "0.8"
rayon = "1.10"
regex = "1.11"
tempfile = "3.2"
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
which = "7.0"
rustpython-parser = "0.3"
tree-sitter = "0.22"
tree-sitter-python = "0.21"
similar = "2.4"
sha2 = "0.10"
toml = "0.8"

[dev-dependencies]
tempfile = "3.8" 