name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-wheels:
    name: Build distribution
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build distribution
        working-directory: python
        run: python -m build
      
      - name: Check distribution
        working-directory: python
        run: |
          twine check dist/*
          ls -la dist/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-distributions
          path: python/dist/

  publish-pypi:
    name: Publish to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fastest-runner
    permissions:
      id-token: write  # For trusted publishing
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-distributions
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  publish-test-pypi:
    name: Publish to Test PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/fastest-runner
    permissions:
      id-token: write
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-distributions
          path: dist/
      
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true 