name: release-plz

on:
  push:
    branches: [main]

permissions:
  contents: write      # push commits, tags, releases
  pull-requests: write # open/update release PRs

jobs:
  # 1) keep the version & changelog in sync – opens/updates a Release PR
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create / update Release PR
        id: release
        uses: release-plz/release-plz-action@v0.6
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 2) after that PR is merged, cut the tag & publish the GitHub release
  release:
    needs: release-pr
    if: ${{ needs.release-pr.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Tag + GitHub Release (+ optional crates.io publish)
        uses: release-plz/release-plz-action@v0.6
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment if you also want `cargo publish` out of the box
          # CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }} 