name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_git_tag: ${{ steps.semantic.outputs.new_release_git_tag }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
        continue-on-error: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache semantic-release
        uses: actions/cache@v4
        id: semantic-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-semantic-release-${{ hashFiles('.releaserc*') }}
          restore-keys: |
            ${{ runner.os }}-semantic-release-

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@10
            @semantic-release/exec@6
            conventional-changelog-conventionalcommits@8

  dist:
    name: Build Distribution
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.dist.outputs.artifacts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.new_release_git_tag }}

      - name: Install dist
        uses: taiki-e/install-action@v2
        with:
          tool: dist

      - name: Run dist plan
        run: dist plan --tag=${{ needs.semantic-release.outputs.new_release_git_tag }} --output-format=json > plan.json

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: dist-plan
          path: plan.json
          retention-days: 1

  build:
    name: Build ${{ matrix.display_name || matrix.targets }}
    needs: [semantic-release, dist]
    if: needs.semantic-release.outputs.new_release_published == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            targets: x86_64-unknown-linux-gnu
            display_name: Linux x64
          - runner: ubuntu-latest
            targets: aarch64-unknown-linux-gnu
            display_name: Linux arm64
          - runner: macos-latest
            targets: x86_64-apple-darwin
            display_name: macOS x64
          - runner: macos-latest
            targets: aarch64-apple-darwin
            display_name: macOS arm64
          - runner: windows-latest
            targets: x86_64-pc-windows-msvc
            display_name: Windows x64
    runs-on: ${{ matrix.runner }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.new_release_git_tag }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true
          prefix-key: v0-rust-${{ matrix.targets }}

      - name: Install dist
        uses: taiki-e/install-action@v2
        with:
          tool: dist

      - name: Install cross-compilation tools
        if: contains(matrix.targets, 'aarch64') && runner.os == 'Linux'
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.targets }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}

      - name: Download dist plan
        uses: actions/download-artifact@v4
        with:
          name: dist-plan

      - name: Build artifacts
        run: |
          dist build --tag=${{ needs.semantic-release.outputs.new_release_git_tag }} --target=${{ matrix.targets }} --output-format=json > dist-output.json
          echo "cargo-dist output:"
          cat dist-output.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.targets }}
          path: target/distrib/*
          retention-days: 1

  publish:
    name: Publish Release
    needs: [semantic-release, build]
    if: needs.semantic-release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.new_release_git_tag }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - name: List artifacts
        run: |
          echo "Downloaded artifacts:"
          find dist -type f -name "*" | sort

      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.sha256
          echo "Checksums:"
          cat checksums.sha256

      - name: Attach artifacts to release
        run: |
          gh release upload ${{ needs.semantic-release.outputs.new_release_git_tag }} dist/* --clobber

      # Crates.io publishing removed - not needed for this project

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/*