name: Release

on:
  push:
    branches: [main]        # default branch
  workflow_dispatch:        # manual trigger

permissions:
  contents: write           # tags, CHANGELOG
  pull-requests: write
  id-token: write           # crates.io publish

jobs:
# ── create / update the Release PR ──────────────────────────
  release-pr:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.rp.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest        # **manifest-driven**
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

# ── publish to crates.io once that PR is merged ─────────────
# Temporarily disabled
#  publish:
#    if: needs.release-pr.outputs.created == 'true'
#    needs: release-pr
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with: {fetch-depth: 0}     # pull tags
#      - uses: dtolnay/rust-toolchain@stable
#      - name: Publish to crates.io
#        env:
#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
#        run: |
#          cargo publish -p fastest-core
#          cargo publish -p fastest-execution
#          cargo publish -p fastest-plugins-macros
#          cargo publish -p fastest-plugins
#          cargo publish -p fastest-advanced
#          cargo publish -p fastest-cli

# ── build and upload binaries to GitHub Releases ────────────
  upload-binaries:
    if: needs.release-pr.outputs.created == 'true'
    needs: release-pr
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Binary name
          bin: fastest
          # Target triple
          target: ${{ matrix.target }}
          # Archive name template
          archive: fastest-$tag-$target
          # Include additional files
          include: LICENSE,README.md
          # Create checksums
          checksum: sha256
          # Build with release profile
          profile: release
          # Path to workspace Cargo.toml
          manifest-path: ./Cargo.toml
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}