name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
# ── Semantic Release (analyze commits, bump version, create tag) ──
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_git_tag: ${{ steps.semantic.outputs.new_release_git_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-edit
        run: cargo install cargo-edit --locked
      
      - name: Create package.json for semantic-release
        run: |
          cat > package.json << 'EOF'
          {
            "name": "fastest-release",
            "version": "0.0.0-development",
            "private": true,
            "devDependencies": {
              "semantic-release": "^19.0.0",
              "@semantic-release/changelog": "^6.0.0",
              "@semantic-release/commit-analyzer": "^9.0.0",
              "@semantic-release/release-notes-generator": "^10.0.0",
              "@semantic-release/exec": "^6.0.0",
              "@semantic-release/git": "^10.0.0",
              "@semantic-release/github": "^8.0.0"
            }
          }
          EOF
      
      - name: Install dependencies
        run: npm install --no-audit
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19

# ── Build and upload binaries when a new release is created ──
  upload-binaries:
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true'
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.new_release_git_tag }}
      
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fastest
          target: ${{ matrix.target }}
          archive: fastest-$tag-$target
          include: LICENSE,README.md
          checksum: sha256
          profile: release
          manifest-path: ./Cargo.toml
          token: ${{ secrets.GITHUB_TOKEN }}
          # Specify the ref to ensure we're uploading to the right release
          ref: refs/tags/${{ needs.semantic-release.outputs.new_release_git_tag }}

# ── Update version manifest after all binaries are uploaded ──
  update-version-manifest:
    needs: [semantic-release, upload-binaries]
    if: needs.semantic-release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update version manifest
        run: |
          ./scripts/update-version-manifest.sh \
            "${{ needs.semantic-release.outputs.new_release_version }}" \
            "${{ needs.semantic-release.outputs.new_release_git_tag }}"
      
      - name: Commit and push version manifest
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/version.json
          git commit -m "chore: update version manifest for ${{ needs.semantic-release.outputs.new_release_git_tag }} [skip ci]" || exit 0
          git push